combined-classification:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 2

kbqa:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 0

factoid-classification:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 0

odqa:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 2

comet-atomic:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 2

comet-conceptnet:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 2

entity-linking:
  CUDA_VISIBLE_DEVICES: "''"

wiki-parser:
  CUDA_VISIBLE_DEVICES: "''"

knowledge-grounding:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 1

midas-classification:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 0

masked-lm:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 1

wikidata-dial-service:
  CUDA_VISIBLE_DEVICES: '0'
  gpu: 1
