compose_override:
  build:
    args:
      SERVICE_PORT: 8107
      SERVICE_NAME: speech_function_predictor
    context: .
    dockerfile: annotators/speech_function_predictor/Dockerfile
  command: uvicorn server:app --host 0.0.0.0 --port 8107
  ports:
  - 8107:8107
  deploy:
    mode: replicated
    replicas: 1
    resources:
      limits:
        memory: 768M
      reservations:
        memory: 768M
compose_dev:
  volumes:
  - ./annotators/speech_function_predictor:/src
  - ./common:/src/common
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 8107:8107
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=lnsigo.mipt.ru:8107
  - PORT=8107
