SERVICE_PORT: 8141
SERVICE_NAME: dff_nutrition_prompted_skill
PROMPT_FILE: common/prompts/nutrition.json
GENERATIVE_SERVICE_URL: http://transformers-lm-oasst12b:8158/respond
GENERATIVE_SERVICE_CONFIG: default_generative_config.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 7
