SERVICE_PORT: 8157
SERVICE_NAME: dff_plan_for_article_prompted_skill
PROMPT_FILE: common/prompts/plan_for_article.json
GENERATIVE_SERVICE_URL: http://openai-api-davinci3:8131/respond
GENERATIVE_SERVICE_CONFIG: openai-text-davinci-003.json
GENERATIVE_TIMEOUT: 10
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
