name: dff-ai-faq-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8143
      SERVICE_NAME: dff_ai_faq_prompted_skill
      PROMPT_FILE: common/prompts/ai_faq.json
      GENERATIVE_SERVICE_URL: http://transformers-lm-oasst12b:8158/respond
      GENERATIVE_SERVICE_CONFIG: default_generative_config.json
      GENERATIVE_TIMEOUT: 10
      N_UTTERANCES_CONTEXT: 7
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8143 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8143:8143
proxy: null
