SERVICE_PORT: 8139
SERVICE_NAME: dff_fairytale_prompted_skill
PROMPT_FILE: common/prompts/fairytale.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
