SERVICE_PORT: 8170
SERVICE_NAME: dff_dream_faq_prompted_skill
PROMPT_FILE: common/prompts/dream_faq.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt-16k:8167/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
