name: agent
endpoints:
- respond
compose:
  command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/management_assistant/pipeline_conf.json'
  environment:
    WAIT_HOSTS: ""
    WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-1000}
    HIGH_PRIORITY_INTENTS: 1
    RESTRICTION_FOR_SENSITIVE_CASE: 1
    ALWAYS_TURN_ON_ALL_SKILLS: 0
    LANGUAGE: EN
    FALLBACK_FILE: fallbacks_sentius_en.json
    FALLBACK_TO_DOCS_FILE: fallbacks_sentius_en_docs.json
    HELP_FILE: help_en.json
    START_DIALOG_FILE: start_dialog_en.json
  volumes:
  - .:/dp-agent
  ports:
  - 4242:4242
proxy: null
