services:
  agent:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/deepy_adv/pipeline_conf.json'
    volumes:
      - ".:/dp-agent"
    environment:
      WAIT_HOSTS: "spelling-preprocessing:8074, harvesters-maintenance-gobot-skill:3882,
        rule-based-response-selector:8005, emotion-classification-deepy:8015, dff-program-y-skill:8008, entity-linking-deepy:8075,
        intent-catcher:8014, sentseg:8011"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-480}

  spelling-preprocessing:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8074
        SERVICE_NAME: spelling_preprocessing
      context: ./annotators/spelling_preprocessing/
    command: flask run -h 0.0.0.0 -p 8074
    environment:
      - FLASK_APP=server
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
    ports:
      - 8074:8074

  harvesters-maintenance-gobot-skill:
    build:
      context: skills/harvesters_maintenance_gobot_skill_deepy
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3882 --timeout=1000
    ports:
      - 3882:3882

  rule-based-response-selector:
    build:
      context: response_selectors/rule_based_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8005
    volumes: []
    ports:
      - 8005:8005

  emotion-classification-deepy:
    build:
      context: annotators/emotion_classification_deepy
    command: python -m deeppavlov riseapi emo_bert.json -p 8015
    ports:
      - 8015:8015

  dff-program-y-skill:
    env_file: [ .env ]
    build:
      args:
        SERVICE_PORT: 8008
        SERVICE_NAME: dff_program_y_skill
        LANGUAGE: EN
      context: .
      dockerfile: ./skills/dff_program_y_skill/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:8008 --reload
    ports:
      - 8008:8008

  entity-linking-deepy:
    build:
      args:
        SERVICE_PORT: 8075
        SERVICE_NAME: entity_linking
        CONFIG: entity_linking_deepy.json
        SRC_DIR: annotators/entity_linking_deepy
      context: ./
      dockerfile: annotators/entity_linking_deepy/Dockerfile
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    ports:
      - 8075:8075
    environment:
      - CUDA_VISIBLE_DEVICES=''

  intent-catcher:
    env_file: [ .env ]
    build:
      context: .
      dockerfile: ./annotators/IntentCatcherTransformers/Dockerfile
      args:
        SERVICE_PORT: 8014
        CONFIG_NAME: intents_model_dp_config.json
        INTENT_PHRASES_PATH: intent_phrases.json
    command: python -m flask run -h 0.0.0.0 -p 8014
    environment:
      - FLASK_APP=server
      - CUDA_VISIBLE_DEVICES=0
    ports:
      - 8014:8014

  sentseg:
    env_file: [ .env ]
    build:
      context: ./annotators/SentSeg/
    command: flask run -h 0.0.0.0 -p 8011
    environment:
      - FLASK_APP=server
    ports:
      - 8011:8011

version: "3.7"
