name: gigachat-plus-api
endpoints:
- respond
- generate_goals
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8189
      SERVICE_NAME: gigachat_plus_api
      PRETRAINED_MODEL_NAME_OR_PATH: GigaChat-Plus
    context: .
    dockerfile: ./services/gigachat_api_lm/Dockerfile
  command: flask run -h 0.0.0.0 -p 8189
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./services/gigachat_api_lm:/src
  - ./common:/src/common
  ports:
  - 8189:8189
proxy: null
