SERVICE_PORT: 8154
SERVICE_NAME: dff_casual_email_prompted_skill
PROMPT_FILE: common/prompts/casual_email.json
GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
GENERATIVE_TIMEOUT: 120
N_UTTERANCES_CONTEXT: 7
