name: anthropic-api-claudev13
endpoints:
- respond
- generate_goals
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8163
      SERVICE_NAME: anthropic_api_claudev13
      PRETRAINED_MODEL_NAME_OR_PATH: claude-v1.2
      CUDA_VISIBLE_DEVICES: '0'
      FLASK_APP: server
    context: .
    dockerfile: ./services/anthropic_api_lm/Dockerfile
  command: flask run -h 0.0.0.0 -p 8163
  environment:
  - CUDA_VISIBLE_DEVICES=0
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./services/anthropic_api_lm:/src
  - ./common:/src/common
  ports:
  - 8163:8163
proxy: null
