SERVICE_PORT: 8156
SERVICE_NAME: dff_official_email_prompted_skill
PROMPT_FILE: common/prompts/official_email.json
GENERATIVE_SERVICE_URL: http://openai-api-davinci3:8131/respond
GENERATIVE_SERVICE_CONFIG: openai-text-davinci-003-long.json
GENERATIVE_TIMEOUT: 20
N_UTTERANCES_CONTEXT: 7
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
