name: dff-dream-persona-davinci3-prompted-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8137
      SERVICE_NAME: dff_dream_persona_prompted_skill
      PROMPT_FILE: common/prompts/dream_persona.json
      GENERATIVE_SERVICE_URL: http://openai-api-davinci3:8131/respond
      GENERATIVE_SERVICE_CONFIG: openai-text-davinci-003-long.json
      GENERATIVE_TIMEOUT: 20
      N_UTTERANCES_CONTEXT: 7
      ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8137 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8137:8137
proxy: null
