services:
  agent:
    volumes:
      - "./assistant_dists/deepy_faq:/dp-agent"
      - "./skill_selectors/:/dp-agent/skill_selectors/"
      - "./state_formatters/:/dp-agent/state_formatters/"
      - "./skills/:/dp-agent/skills/"
      - "./common/:/dp-agent/common/"
    environment:
      WAIT_HOSTS: "spelling_preprocessing:3771, faq_skill:3772, rule_based_response_selector:3773,
        emotion_classification:3774, dff-program-y:3775"
      WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-480}

  spelling_preprocessing:
    build:
      context: annotators/spelling_preprocessing
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3771 --timeout=100
    ports:
      - 3771:3771

  faq_skill:
    build:
      context: skills/faq_skill_deepy
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3772 --timeout=1000
    ports:
      - 3710:3710

  rule_based_response_selector:
    build:
      context: response_selectors/rule_based_response_selector
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3773
    volumes: []
    ports:
      - 3773:3773

  emotion_classification:
    build:
      context: annotators/emotion_classification_deepy
    command: python -m deeppavlov riseapi emo_bert.json -p 3774
    ports:
      - 3774:3774

  dff-program-y:
    env_file: [.env]
    build:
      args:
        SERVICE_PORT: 3775
        SERVICE_NAME: dff_program_y
      context: .
      dockerfile: ./skills/dff_program_y/Dockerfile
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3775 --reload
    ports:
      - 3775:3775
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 1024M

version: "3.7"
