name: dff-reasoning-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8169
      SERVICE_NAME: dff_reasoning_skill
      GENERATIVE_SERVICE_URL: http://openai-api-chatgpt:8145/respond
      GENERATIVE_SERVICE_CONFIG: openai-chatgpt.json
      GENERATIVE_TIMEOUT: 30
      N_UTTERANCES_CONTEXT: 3
      ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY,OPENWEATHERMAP_API_KEY,NEWS_API_KEY,WOLFRAMALPHA_APP_ID
    context: .
    dockerfile: ./skills/dff_api_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8169 --reload
  deploy:
    resources:
      limits:
        memory: 1.5G
      reservations:
        memory: 1.5G
  volumes:
  - ./skills/dff_reasoning_skill:/src
  - ./common:/src/common
  - "./skills/dff_weather_skill/tools:/src/tools"
  - "./skills/dff_weather_skill/data:/src/data"
  ports:
  - 8169:8169
proxy: null
